### ISSUE TITLE
Requesting paper

### ISSUE THREAD

**Issue by stephvino** [shshen-closer/Convolutional-Knowledge-Tracing#1]
Dear author,
    Hello. I'm a student currently studying knowledge tracing. I've read your code, your work is fascinating! However, I can't find your paper on the internet, can you please provide a way to read your paper?
    Thank you.Looking forward to your reply!

**Comment by shshen-closer** [comment]
Hello, thanks for your attention！ The paper was recently accepted by SIGIR2020 as a short paper, which is still in the submission process and not published. If you want to read in as soon as possible, you may leave me an email address. Thank you!

**Comment by stephvino** [comment]
Sorry, didn't expect your response so soon!
Congratulations on your acceptance! It is greatly appreciated for your kind offer, this is my email address:
cs_weiwang@foxmail.com.
With best wishes, thank you!
