### ISSUE TITLE
库版本

### ISSUE THREAD

**Issue by csxuhuan** [shshen-closer/Convolutional-Knowledge-Tracing#5]
你好，请求一下代码复现的库版本号。

以下是我的配置：
Python 3.7
Numpy 1.21.1
tensorflow 1.15.0
sklearn 1.0.1
运行时一直会出现错误

希望能给出requirement.txt

**Comment by shshen-closer** [comment]
您好，来信已收到

**Comment by csxuhuan** [comment]
已调通，感谢，close issue了
